apiVersion: v1
kind: Service
metadata:
  name: cicd-jenkins-kubernetes-service
spec:
  selector:
    app: cicd-jenkins-kubernetes 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 30000
